<?php
/**
 * OK Open button template
 *
 * @var $block \Okitcom\OkLibMagento\Block\Button\Open
 */
?>
<?php if (!$block->isLoggedIn()) { ?>
    <button id="ok-open-button" data-mage-init='{ "Okitcom_OkLibMagento/okopen": { } }' class="btn ok-action-button-default icon-right icon-horizontal">
        <span class="ok-button-icon"></span>
        <span class="ok-button-text"><?php echo __('Log in with') ?></span>
    </button>
<?php } ?>


