<?php
/**
 * OK Checkout button template
 *
 * @var $block \Okitcom\OkLibMagento\Block\Button\Checkout
 */
?>
<button id="ok-checkout-button"
        click="open"
        class="btn ok-action-button-default icon-right icon-horizontal"
        data-mage-init='{ "Okitcom_OkLibMagento/okcheckout": { } }'>
    <span class="ok-button-icon"></span>
    <span class="ok-button-text"><?php echo __('Quick checkout with') ?></span>
</button>